#cloud-config
package_update: true
package_upgrade: true

runcmd:
  # Install dependencies
  - apt update && apt upgrade -y && apt install -y apt-transport-https ca-certificates curl git containerd

  # Install Docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - apt update && apt install -y docker.io
  - systemctl enable docker

  # Install Kubernetes
  - curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-archive-keyring.gpg
  - echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /" | tee /etc/apt/sources.list.d/kubernetes.list
  - apt update && apt install -y kubelet kubeadm kubectl
  - systemctl enable kubelet

  # Join Kubernetes cluster
  - sudo kubeadm join 192.168.1.111:6443 --token qj5yn6.hnj4msokhve52gn5 --discovery-token-ca-cert-hash sha256:49dc481a5604ce9e4e2f60148e6a938aa30e89305fd0b524eea83250d4e81704

  # Wait for Kubernetes to be ready
  - sleep 60

  # Install Helm
  - curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

  # Deploy Kafka using Helm
  - helm repo add bitnami https://charts.bitnami.com/bitnami
  - helm install kafka bitnami/kafka --set replicaCount=1

  # Deploy Cassandra using Helm and 
  - helm install cassandra bitnami/cassandra --set replicaCount=1

  # Deploy Grafana using Helm
  - helm install grafana bitnami/grafana --set service.type=NodePort

  # Clone the threat intelligence scraping scripts from GitHub
  - git clone https://github.com/att3v/dsp2025.git /home/ubuntu/dsp2025

  # Apply Kubernetes deployment for threat intelligence scraper
  # - kubectl apply -f /home/ubuntu/threat-intel/threat-intel-scraper.yaml
