apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scraper
  template:
    metadata:
      labels:
        app: scraper
    spec:
      containers:
        - name: scraper-producer
          image: att3v/data-producer:latest
          env:
            - name: KAFKA_BROKER
              value: "kafka.kafka.svc.cluster.local:9092"
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
