apiVersion: v1
kind: Service
metadata:
  name: scraper-service
spec:
  selector:
    app: scraper
  ports:
    - protocol: TCP
      port: 80         # Service port
      targetPort: 8000 # FastAPI running inside the pod
      nodePort: 30080  # Port exposed on the worker node
  type: NodePort