apiVersion: apps/v1
kind: Deployment
metadata:
  name: cve-consumer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cve-consumer
  template:
    metadata:
      labels:
        app: cve-consumer
    spec:
      containers:
      - name: cve-consumer
        image: att3v/data-consumer:latest
        env:
        - name: KAFKA_BROKER
          value: "kafka.kafka.svc.cluster.local:9092"
        - name: CASSANDRA_HOSTS
          value: "cassandra.cassandra.svc.cluster.local:9042"
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
